# Generated by Django 5.0.1 on 2024-01-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='createdBy',
        ),
    ]
