# Generated by Django 5.0.1 on 2024-01-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_menu_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='numReviews',
        ),
    ]
