# Generated by Django 5.0.1 on 2024-01-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userprofile_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.restaurant'),
        ),
    ]
