# Generated by Django 5.0.1 on 2024-01-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_paymentinfo_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='client_secret',
            new_name='clientSecret',
        ),
    ]
